# Generated by Django 3.0.1 on 2020-06-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Done',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='listtodo',
            name='alreadydone',
        ),
    ]
