# Generated by Django 3.0.1 on 2020-06-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200630_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='done',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listtodo',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
